# Generated by Django 3.0.5 on 2020-05-01 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vendor', '0015_auto_20200430_1730'),
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomersList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('customers', models.ManyToManyField(related_name='lists', to='Customer.Customer')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='Vendor.Vendor')),
            ],
        ),
    ]
