# Generated by Django 3.0.5 on 2020-04-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_auto_20200414_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='imported',
            field=models.BooleanField(default=False),
        ),
    ]
