# Generated by Django 3.0.5 on 2020-05-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendor', '0001_initial'),
        ('Customer', '0002_auto_20200502_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerslist',
            name='mail_campaigns',
            field=models.ManyToManyField(related_name='lists', to='Vendor.MailCampaign'),
        ),
    ]
