# Generated by Django 3.0.5 on 2020-05-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_customerslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerslist',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
