# Generated by Django 3.0.5 on 2020-04-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_auto_20200421_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertoken',
            name='token',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
