# Generated by Django 3.0.5 on 2020-04-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='poster',
            field=models.FileField(blank=True, default=None, null=True, upload_to='tranings/posters/'),
        ),
    ]
