# Generated by Django 3.0.5 on 2020-04-24 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_training_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
