# Generated by Django 3.0.5 on 2020-04-30 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vendor', '0015_auto_20200430_1730'),
        ('Admin', '0003_training_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('responded', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='Vendor.Vendor')),
            ],
        ),
    ]
